# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Dependencies
markdown:         kramdown
highlighter:      Rouge
exclude: 		  [node_modules/, package.json ]
Include: 		  [.htaccess]

kramdown:
  input: GFM

# Site settings
title: Aleut.css
email: knut@netliferesearch.com
description: > # this means to ignore newlines until "baseurl:"
  Aleut is a fork of inuitcss. It is a powerful, Sass-based, BEM, OOCSS framework designed with scalability and performance in mind.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aleutcss.github.io" # the base hostname & protocol for your site
github_username:  aleutcss

sass:
